language: python
sudo: false
env:
  global:
    BUILD_DOCS_BRANCH: master
    DOCS_SUBDIR: doc/
    TARGET_DEV_SUBDIR: bluesky/
    HTML_SUBDIR: build/html
    DOCS_CONDA_DEPS: "bluesky"
    DOCS_PIP_DEPS: "tqdm"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

matrix:
  include:
    - python: 3.6
      env: BUILD_DOCS=true

before_install:
  - git clone https://github.com/NSLS-II/nsls2-ci --branch master --single-branch ~/ci_scripts
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - conda config --set show_channel_urls True
  - conda config --set always_yes True

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv nose python=$TRAVIS_PYTHON_VERSION scipy ipython jsonschema pytest coverage pip ophyd pyepics mock xlrd pyfai flake8 codecov -c lightsource2-tag -c conda-forge -c soft-matter
  - source activate testenv
  - pip install https://github.com/NSLS-II/databroker/zipball/master#egg=databroker
  - pip install https://github.com/NSLS-II/bluesky/zipball/master#egg=bluesky
  - pip install https://github.com/xpdAcq/xpdAcq/zipball/master#egg=xpdan
  - pip install .
  - python -c "from bluesky.utils import get_history; get_history()"
  - python -c "from xpdsim import xpd_pe1c; xpd_pe1c.trigger_read()"
  - git clean -xfd

script:
  - coverage run run_tests.py
  - coverage report -m

after_script:
  - flake8
  - codecov
