package:
  name: xpdsim
  version: '1.0.1'
source:
  git_rev: master
  git_url: http://github.com/chiahaoliu/xpdSim.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - ophyd
    - bluesky

about:
  home: https://github.com/chiahaoliu/xpdSim
